# Email Scheduler for Solar Assistant
#
# Author: Stefan Verster
# Copyright © 2025 Stefan Verster
#
# This code is available for personal and non-commercial use.
# If you find this software useful, please consider supporting the author by making a donation:
# https://www.paypal.com/donate/?hosted_button_id=2YZ4F42REQX4C
#
# Thank you for your support!

version: '3.8'

services:
  solarassistant-reports:
    container_name: solarassistant-reports
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"  # Optional for future dashboard
